<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestDataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f20d7b21-2d47-44d7-8ed0-436698b53a52</testSuiteGuid>
   <testCaseLink>
      <guid>ffffd831-dcc7-4cd2-b7c8-cddc718bf948</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestDataDrivenFile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>289f08fe-7719-4f71-9f3d-4fb9f56b1dbc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/testData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>289f08fe-7719-4f71-9f3d-4fb9f56b1dbc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>b89899fc-ffcf-4931-8f05-66086583e6b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6433cfcf-afc8-49f7-b989-52c536c61695</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
