<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Trello</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8046b227-c9d3-49a7-95ea-62c36edcac00</testSuiteGuid>
   <testCaseLink>
      <guid>cfeadc4b-1167-4193-ac3b-0bb3ef3389a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Trello Api Automation/TC01 Login - Board Creation - Logout</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d22ec6f4-33f8-4962-a812-ea8628883b83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51c593d2-03aa-4753-a7de-8e67ecffeb8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0508e38b-20aa-4e2c-a314-a2ec5998823e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a05f7f9-a393-4fce-af70-bcd7fabc3d92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Trello Api Automation/TC02 Login - Board Creation - List Creation - Card Creation - logout</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c78a90f8-b7c9-41de-919d-1796c0de3824</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7197c796-2f25-48bf-8b90-f3da46db919f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce03a5af-f432-4f7f-acbc-65ee84ce1c03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c58a57f3-a4d2-4248-8add-687f00143127</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b44071b-7b5b-4045-b6ad-ab717122c922</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c24bd44-1168-48c4-ab9a-79a02dbaaac1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Trello Api Automation/TC03 Board Creation - Update the Board</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62c95e12-4c47-45eb-8259-9c6dc42d9291</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1a758e6-ed02-43df-a994-34a3746c9084</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0b94fe7-806a-451a-92f2-1eaea0abb101</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ffba264-58d7-4f7e-bf2f-9b280818d121</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Trello Api Automation/TC04 Board - List - Card - Update Card Details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e9ba5b9-676e-4c85-a89a-959fd8d1e2b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5442f906-d0c8-4e35-8987-dd9bc9dc94f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e2bebe1-7c35-42bf-93ae-9eec515e5b42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>632ab75d-d461-4f5e-a300-7475da30e5af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70ea146a-a448-4cee-9d81-040958089d06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b06b22aa-bbaf-4e5f-8386-41d8f8811a80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Trello Api Automation/TC05 Create a List - Get the data from List - Update the List - Archive the List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21ae3758-08dd-4401-9d52-13f7ca1f3008</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fbeae2e-cdee-4eee-8422-81ad4b9abc41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>682e75b6-d96c-4fbc-8dc6-6edaacc4acb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee63cbda-99c1-4d8a-919b-941c8cca3ebb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9208c904-ba29-460c-aa77-2b2f84b88e74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12e0785b-24aa-45a3-a660-68778436dd70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Trello Api Automation/TC06 Create a Checklist on a Card - Get Checklist on a Card - Delete a Checklist on a Card</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1e76796-695c-4542-91b5-6eee9d76bf7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35fa55b4-51d5-4727-bb0a-ca871704569b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d81139f-bb4d-4ad1-8fb0-76e9c1efab52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a64d46d-892e-4d7c-b545-0705a9ae209e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>227b4b47-0470-4a5b-a873-df2e03f36a7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7344c480-ec33-4c2c-9eae-cddf753a34b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Trello Api Automation/TC07 Create Checkitem in a Checklist - Get a Checkitem - Update the Checkitem - Delete a Checkitem</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>154215c0-2c9d-4ff1-a748-050e7e285fc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>534783db-51e4-40d4-ba75-81ebc4652c21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d121b659-453e-416e-b740-1136b22b8bec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d86bc25-9bc0-4838-9e7e-a0caa62ca6c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c98f6855-8f90-4091-84b6-6368dc3b1add</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c33241e-ba5e-4485-902e-aebe37356258</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a48b00f6-450e-44a1-bf01-4ad064763428</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de93ac45-8d57-4496-af12-a4a0ddcf76f6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
